EventManagement/Controllers/OccationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using EventManagement.Models;
using System.Data.Objects;
using EventManagement.Utilities;

namespace EventManagement.Controllers
{
    public class OccationController : Controller
    {
        //
        // GET: /Occation/

        EventManagementEntities db = new EventManagementEntities();

        public ActionResult GetAllEvent()
        {
            try
            {
                string dateRange = Request.Form["ddlDateFilter"];
                List<CutomerEventViewModel> events = new List<CutomerEventViewModel>();
                EventManagementEntities db = new EventManagementEntities();
                if (dateRange != null)
                {
                    double startRange = 0, endRange = 0;
                    if (dateRange == "less than 50 days")
                    {
                        startRange = 1;
                        endRange = 49;
                    }
                    else if (dateRange == "50-100 days")
                    {
                        startRange = 50;
                        endRange = 100;
                    }
                    else if (dateRange == "greater than 100 days")
                    {
                        startRange = 101;
                        endRange = 365;
                    }
                    events = (from c in db.Customers
                              join e in db.Events on c.evntID equals e.evntID
                              where c.custDtFrom.HasValue
                              && c.custDtTo.HasValue
                              && EntityFunctions.DiffDays(c.custDtTo.Value, DateTime.Now) > startRange
                              && EntityFunctions.DiffDays(c.custDtTo.Value, DateTime.Now) < endRange
                              select new CutomerEventViewModel
                              {
                                  EventId = e.evntID,
                                  EventName = e.evntName,
                                  CustomerName = c.custName,
                                  CustomerEmail = c.custEmail,
                                  PeopleCount = 0,
                                  DateFrom = c.custDtFrom.Value,
                                  DateTo = c.custDtTo.Value,
                                  SpecialAsk = c.custSpacialAsk
                              }).ToList();
                }
                else
                {
                    events = (from c in db.Customers
                              join e in db.Events on c.evntID equals e.evntID
                              where c.custDtFrom.HasValue && c.custDtTo.HasValue
                              select new CutomerEventViewModel
                              {
                                  EventId = e.evntID,
                                  EventName = e.evntName,
                                  CustomerName = c.custName,
                                  CustomerEmail = c.custEmail,
                                  PeopleCount = 0,
                                  DateFrom = c.custDtFrom.Value,
                                  DateTo = c.custDtTo.Value,
                                  SpecialAsk = c.custSpacialAsk
                              }).ToList();
                }

                return View(events);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Source, ex.Message);
                return RedirectToAction("CreateEvent", "Event");
            }
        }

        public void SendEmail(FormCollection form)
        {
            try
            {
                var selectedIds = form.GetValues("chkSelected");
                if (selectedIds != null)
                {
                    EventManagementEntities db = new EventManagementEntities();
                    foreach (var id in selectedIds)
                    {
                        if (id != "false")
                        {
                            string email = (from c in db.Customers where c.evntID.Value.ToString() == id select c.custEmail).FirstOrDefault();
                            if (!string.IsNullOrEmpty(email))
                            {
                                //SendEmail                               
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Source, ex.Message);
            }
        }

        public ActionResult GetPlaceByEventId(Int32 eventId)
        {
            EventManagementEntities db = new EventManagementEntities();

            var services = from s in db.Services
                           join es in db.EventServices on s.svcID equals es.svcID
                           join e in db.Events on es.evntID equals e.evntID
                           where e.evntID == eventId
                           select new
                           {
                               id = s.svcID,
                               name = s.svcName
                           };

            //db.LocationAddresses.Where(c => c.locID == locationId);
            return Json(services, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetPlaceByEventIds(string eventIds)
        {
            EventManagementEntities db = new EventManagementEntities();

            //var services = from s in db.Services
            //               join es in db.EventServices on s.svcID equals es.svcID
            //               join e in db.Events on es.evntID equals e.evntID
            //               where eventIds.Contains(e.evntID.ToString()) //= (eventIds
            //               select new
            //               {
            //                   id = s.svcID,
            //                   name = s.svcName
            //               };

            //JavaScriptSerializer serializer = new JavaScriptSerializer();
            //var obj = serializer.Deserialize<Dictionary<string, object>>(eventIds);

            dynamic dynObj = JsonConvert.DeserializeObject(eventIds);
            //Array dd = new Array[] {  dynObj.eId  };

            var arr = dynObj["eId"];

             //int[] myInts = Array.ConvertAll(arr, int.Parse);

            string ed = string.Empty;

            foreach (var it in arr)
            {
                ed += "," + it.ToString();
            }
            ed = ed.Remove(0, 1);

            var idList = new string[] { };
            idList = ed.Split(',');
            int[] myInts = Array.ConvertAll(idList, int.Parse);


            var services = from s in db.Services
                           join es in db.EventServices on s.svcID equals es.svcID
                           join e in db.Events on es.evntID equals e.evntID
                           where myInts.Contains(e.evntID)
                           select new
                           {
                               id = s.svcID,
                               name = s.svcName
                           };

            //db.LocationAddresses.Where(c => c.locID == locationId);
            return Json(services, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetAllServiceProvider()
        {
            try
            {
                List<ServicesViewModel> lstsSrvicePro = new List<ServicesViewModel>();
                //CutomerEventViewModel vmCustEvent = new CutomerEventViewModel();

                var details = from sp in db.ServiceProviders
                              select new
                              {
                                  Id = sp.spId,
                                  ProviderEmail = sp.spEmail,
                                  Providername = sp.spName,
                                  ProviderPhone = sp.spPhone,
                                  NoOfImages = sp.spUploadImage,
                                  Company = sp.spCompanyName
                              };

                foreach (var item in details)
                {
                    ServicesViewModel vmProvider = new ServicesViewModel();

                    vmProvider.Id = item.Id;
                    vmProvider.ProviderName = item.Providername;
                    vmProvider.ProviderEmail = item.ProviderEmail;
                    vmProvider.ProviderPhone = item.ProviderPhone;
                    vmProvider.NoOfImages = Convert.ToInt16(item.NoOfImages);
                    vmProvider.ProviderCompany = item.Company;

                    lstsSrvicePro.Add(vmProvider);
                }

                return View("GetAllServiceProvider", lstsSrvicePro);
            }
            catch (System.Exception ex)
            {
                ModelState.AddModelError(ex.Source, ex.Message);
                return RedirectToAction("CreateEvent", "Event");
            }
        }

        public ActionResult DisplaySPImages(int id)
        {
            var lstimages = (from sp in db.ServiceProviders
                             join img in db.ImageUploads on sp.spId equals img.ImgUploaderId
                             where sp.spId == id
                             select new EventManagement.Models.ImageUpload
                             {
                                 Image = img.Image
                             });
            return PartialView("_GetSPImages", lstimages);
        }

    }
}

EventManagement/Views/Occation/GetAllEvent.cshtml
@model IEnumerable<EventManagement.Models.CutomerEventViewModel>
@using GridMvc.Html
@{
    ViewBag.Title = "GetAllEvent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "less than 50 days",
        Value = "less than 50 days"
    });
    listItems.Add(new SelectListItem
    {
        Text = "50-100 days",
        Value = "50-100 days"
    });
    listItems.Add(new SelectListItem
    {
        Text = "greater than 100 days",
        Value = "greater than 100 days"
    });
}
<h2>
    GetAllEvent</h2>
@using (Html.BeginForm("GetAllEvent", "Occation", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="form-group">
            @Html.Label("How many invitees you expect", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ddlDateFilter", listItems, "--Please Select--", new { @class = "form-control" })
                <span style="color: #EF5F5F; font-weight: bold;">*</span>
                <br />
                <span id="spInv" style="color: #EF5F5F; font-weight: bold; display: none;">Please select
                    Invitees</span> @*@Html.ValidationMessageFor(m => m.State, "", new { @class = "text-danger" }) *@
            </div>
            <br />
            <p>
                <input type="submit" value="Search" class="btn btn-previous" />
            </p>
        </div>
    </fieldset>
}

@using (Html.BeginForm("SendEmail", "Occation", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    @Html.Grid(Model).Columns(columns =>
{
    columns.Add().Encoded(false).Sanitized(false).RenderValueAs(o => Html.CheckBox("chkSelected", false, new { value = o.EventId }));
    columns.Add(o => o.EventId,true).Titled("EID");
    columns.Add(o => o.EventName).Titled("Occassion");
    columns.Add(o => o.CustomerName).Titled("Customer Name");
    columns.Add(o => o.CustomerEmail).Titled("Customer Email");
    columns.Add(o => o.PeopleCount).Titled("No. of Invitees");
    columns.Add().Titled("Event Date").RenderValueAs(o => o.DateFrom.ToString("dd/MM/yyyy") + " - " + o.DateTo.ToString("dd/MM/yyyy"));
    //columns.Add(o => o.DateFrom).Titled("Starts").SetWidth(100);
    //columns.Add(o => o.DateTo).Titled("Ends").SetWidth(100);
    columns.Add(o => o.SpecialAsk).Titled("Special Ask");    
 @*columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(d => @<b>@Html.ActionLink("Edit", "EditCustomerEvent", new { customerId = d.CustomerId })</b>);
 columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(d => @<b>@Html.ActionLink("Delete", "DeleteCustomerEvent", new { customerId = d.CustomerId })</b>);*@
}).WithPaging(10).Sortable().Filterable().WithMultipleFilters()

            <p>
                <input type="submit" value="Send Email" class="btn btn-previous" />
            </p>

}


EventManagement/Views/Occation/GetAllServiceProvider.cshtml
@model IEnumerable<EventManagement.Models.ServicesViewModel>
@using GridMvc.Html

@{
    ViewBag.Title = "GetAllServiceProvider";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Service Provider</h2>

@using (Html.BeginForm("SendEmail", "Occation", FormMethod.Post))
{
    @Html.ValidationSummary(true)

@Html.Grid(Model).Columns(columns => {    
    columns.Add(o => o.ProviderName).Titled("Name").SetWidth(50);
    columns.Add(o => o.ProviderPhone).Titled("Phone").SetWidth(50);
    columns.Add(o => o.ProviderEmail).Titled("Email").SetWidth(50);
    columns.Add(o => o.ProviderCompany).Titled("Company").SetWidth(50);
    columns.Add(o => o.Id).Titled("Service Provider Images").Sanitized(false)
     .Encoded(false)
     .RenderValueAs(o => Html.ActionLink("View Image", "DisplaySPImages", new { id = o.Id }, new { @class = "modal-link" }).ToHtmlString());
    //.RenderValueAs(o => Html.ActionLink("View Image", "DisplaySPImages", new { id = o.Id }, null).ToHtmlString());
    columns.Add().Encoded(false).Sanitized(false).RenderValueAs(o => Html.CheckBox("chkSelected", false, new { value = o.Id }));
 @*columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(d => @<b>@Html.ActionLink("Edit", "EditCustomerEvent", new { customerId = d.CustomerId })</b>);
 columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(d => @<b>@Html.ActionLink("Delete", "DeleteCustomerEvent", new { customerId = d.CustomerId })</b>);*@
}).WithPaging(10).Sortable().Filterable().WithMultipleFilters()
            
    
    <p>
      <input type="submit" value="Send Email" class="btn btn-previous" />
    </p>
    
    <div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
        <a href="#close" title="Close" class="modal-close-btn">X</a>
        <div class="modal-content">
        </div>
    </div>

}



<style type="text/css">
     .modal-content {
         width: 600px !important;
         margin: 30px auto !important;
     }
</style>

@section Scripts {
<script type="text/javascript">
    $(function () {
        // Initialize numeric spinner input boxes
        //$(".numeric-spinner").spinedit();
        // Initialize modal dialog
        // attach modal-container bootstrap attributes to links with .modal-link class.
        // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
        $('body').on('click', '.modal-link', function (e) {
            e.preventDefault();
            $(this).attr('data-target', '#modal-container');
            $(this).attr('data-toggle', 'modal');
        });
        // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
        $('body').on('click', '.modal-close-btn', function () {
            $('#modal-container').modal('hide');
        });
        //clear modal cache, so that new content can be loaded
        $('#modal-container').on('hidden.bs.modal', function () {
            $(this).removeData('bs.modal');
        });        
    });
    </script>
    }

EventManagement/Views/Occation/_GetSPImages.cshtml
@model IEnumerable<EventManagement.Models.ImageUpload>
@{
    ViewBag.Title = "GetSPImages";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Service Provider Images</h2>
<div class="modal-body">
    <div class="alert alert-warning">
        @*<div class="container">
              <div class="navbar">
                    <div class="navbar-inner" style="background-image: none;">*@
                         <ul class="nav">
        @{

            foreach (var item in Model)
            {
                byte[] photo = item.Image;
                string imageSrc = null;
                if (photo != null)
                {
                    MemoryStream ms = new MemoryStream();
                    ms.Write(photo, 0, photo.Length);
                    string imageBase64 = Convert.ToBase64String(ms.ToArray());
                    imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                }
        
                <li><img src="@imageSrc" alt="Image" width="100px" height="100px"/></li>
            } 
     
        }
    
                          </ul>
                     </div>
              </div>
        @*</div> 
        </div>
        </div>    *@